import { derToPem, pemToDer } from './pem';

/**
 * Port of encryption/key_manager.py.
 *
 * RSA-2048 with OAEP/SHA-256, matching the desktop app exactly so keys and
 * encrypted files are interchangeable between the two.
 *
 * One place the browser is STRONGER than the desktop app: the desktop version
 * writes an unencrypted PKCS8 PEM to ~/Documents/LLM_Bundler/keys/, readable by
 * anything on the machine. Here the private key lives in IndexedDB as a CryptoKey.
 * It is generated extractable only because interoperability with the Python CLI
 * requires being able to export it — but export is an explicit user action, not
 * something that happens on disk by default.
 */

const KEY_ALGORITHM: RsaHashedKeyGenParams = {
  name: 'RSA-OAEP',
  modulusLength: 2048,
  publicExponent: new Uint8Array([0x01, 0x00, 0x01]), // 65537, same as Python
  hash: 'SHA-256',
};

export interface KeyPairPem {
  privateKeyPem: string;
  publicKeyPem: string;
}

export async function generateKeyPair(): Promise<CryptoKeyPair> {
  return crypto.subtle.generateKey(KEY_ALGORITHM, true, ['encrypt', 'decrypt']);
}

/** Export to the same PEM encoding Python's cryptography library writes. */
export async function exportKeyPair(pair: CryptoKeyPair): Promise<KeyPairPem> {
  const [spki, pkcs8] = await Promise.all([
    crypto.subtle.exportKey('spki', pair.publicKey),
    crypto.subtle.exportKey('pkcs8', pair.privateKey),
  ]);

  return {
    publicKeyPem: derToPem(spki, 'PUBLIC KEY'),
    privateKeyPem: derToPem(pkcs8, 'PRIVATE KEY'),
  };
}

/** Import a PEM public key — e.g. one generated by the desktop app. */
export async function importPublicKeyPem(pem: string): Promise<CryptoKey> {
  return crypto.subtle.importKey('spki', pemToDer(pem), KEY_ALGORITHM, true, ['encrypt']);
}

/** Import a PEM private key — e.g. one generated by the desktop app. */
export async function importPrivateKeyPem(pem: string): Promise<CryptoKey> {
  return crypto.subtle.importKey('pkcs8', pemToDer(pem), KEY_ALGORITHM, true, ['decrypt']);
}
